name: Build and Release

on:
  push:
    branches: [main]
    # Only trigger on direct pushes to main, not from PRs
    
# Ensure only trusted pushes trigger releases
permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: macos-13      # Intel runner for x64 DMG
            platform: macos-intel
            arch: x64
          - os: macos-latest  # ARM64 runner for arm64 DMG  
            platform: macos-arm64
            arch: arm64
          - os: windows-latest # Windows runner for EXE
            platform: windows
            arch: x64
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Build macOS distribution
      if: startsWith(matrix.platform, 'macos')
      run: npm run dist:mac -- --${{ matrix.arch }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Windows distribution
      if: matrix.platform == 'windows'
      run: npm run dist:win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-build
        path: |
          release/*.dmg
          release/*.exe
        retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && github.repository == 'davidtstafford/stream-mesh'
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Get package version
      id: version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
    - name: Download Intel macOS artifacts
      uses: actions/download-artifact@v4
      with:
        name: macos-intel-build
        path: ./artifacts/
        
    - name: Download ARM64 macOS artifacts
      uses: actions/download-artifact@v4
      with:
        name: macos-arm64-build
        path: ./artifacts/
        
    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: windows-build
        path: ./artifacts/
        
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "v${{ steps.version.outputs.version }}" \
          --title "Stream Mesh v${{ steps.version.outputs.version }}" \
          --notes "Automated release for Stream Mesh v${{ steps.version.outputs.version }}" \
          ./artifacts/*.dmg \
          ./artifacts/*.exe
